version: '3.8'

services:
  eureka:
    image: eureka
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8761:8761
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge